version: '2.1'

services:
  blockchain:
    container_name: blockchain_node
    build:
      context: ./blockchain
      dockerfile: ./Dockerfile
    ports:
      - "8545:8545"
  blockchain-deployer:
    container_name: blockchain_deployer
    build:
      context: ./smart contracts
      dockerfile: ./Dockerfile
    environment:
      - HOST=http://docker.for.mac.host.internal:8545
      - PRIVATE_KEY=0x4d5db4107d237df6a3d58ee5f70ae63d73d7658d4026f2eefd2f204c81682cb7
    depends_on:
      - blockchain